# Moonraker Configuration File

[server]
host: 0.0.0.0
port: 7125
# Make sure the klippy_uds_address is correct.  It is initialized
# to the default address.
klippy_uds_address: /home/klipper/printer_data/comms/klippy.sock

[machine]
provider: systemd_dbus


[authorization]
force_logins: False
cors_domains:
    *.local
    *.lan
    *://localhost
    *://localhost:*
    *://app.fluidd.xyz
    *://my.mainsail.xyz
trusted_clients:
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FE80::/10
    ::1/128
[file_manager]
enable_object_processing: False
[history]
[octoprint_compat]
[update_manager]
refresh_interval: 168
enable_auto_refresh: True
[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: /var/www/mainsail
